### PR TITLE
Fixed the passing of multiple cia files to transit (issue #13)

### PR DESCRIPTION
**Pull request by AndrewSDFoster**
Sorry for the merge-then-reversion, go with this one.

### CODE REVIEW

**Comment by aj-foster** [comment]
I'm a bit confused. The diff on this pull request only shows one commit in which the comments were changed. I think you need to pull down from master and create new commits (more importantly, new commit hashes) with the actual changes.

**Comment by AndrewSDFoster** [comment]
The first two commits got added then reverted in the main code, so they aren't showing up in the diff for some reason. Look in my branch and in the master and compare the two files and you'll see the full changes. Things got really weird because of the reversion.

**Comment by AndrewSDFoster** [comment]
I think that the best thing to do at this point is to make a whole new branch and redo the changes and recommit. At least we've learned a lesson.

**Comment by ccampo133** [comment]
Usually this can be fixed with rebase.

**Comment by aj-foster** [comment]
Please don't rebase a history that others have pulled. If we had caught it sooner, that would be fine.

**Comment by aj-foster** [comment]
Though, I'm guessing you meant that he should rebase his local copy of the branch; does that work with commit SHAs that have already part of the history?

**Comment by ccampo133** [comment]
Rebasing a pushed (remote) branch is usually fine so long as nobody has pulled. If you have people that HAVE pulled, then yes of course, be sure to sync with them before pushing. Of course, this will also require a `push --force` to work.

Since this is a pull request, I was recommending that @AndrewSDFoster just rebase (and/or reset and cherry-pick from his main (master?) branch) his `multicia` branch to fix the changes and then push to his repository. This will update the pull request with the correct changes without effecting this repository.

@aj-foster, I'm not sure I follow your question... but rebasing will create totally new commit hashes and remove any previous ones that you are overwriting. Technically they will still exist in the reflog if for some reason you would need to recover them.

**Comment by sdb05c** [comment]
So in plain speak- in the transit.cfg file can I just list multiple CIA files and it will know what to do? Or do I need to set a flag in the config file? (Also, same questions but just for the tli files). ..having a hard time following the github convo

**Comment by pcubillos** [comment]
Any final verdict @AndrewSDFoster , @aj-foster , @ccampo133 ?  Should I merge or no?

@sdb05c: Multiple CIA files won't work until I merge. Multiple TLI files is work in progress by Andrew, should take a couple of days, probably.  Advise: If you are in a hurry, go with the H2-H2 CIA file (H2-He is a minor contribution). As for TLI, put all species into a single TLI, and pass that to Transit/BART.

**Comment by ccampo133** [comment]
I'll take a look at the commit when I get on my laptop. On my phone at the
moment.

**Comment by aj-foster** [comment]
Closing. @AndrewSDFoster, unless there are any changes to make, I'm going to work with your previous commits in a separate pull request. Because GitHub does a history-preserving revert, your commits are already in the history of master and can't be merged in again. We've learned, and in the future we won't have this issue.

@pcubillos, expect another pull request soon with the same contents as Andrew's original request. Please look over it and merge at your discretion.

**Pull request closed without merging**
