### PR TITLE
Added abundance profile plotting. Fixed uniform atm file path bug. Ad…

### PR DESCRIPTION
**Pull request by rychallener**
…justed tick marks in best fit spectrum in case of strange lower wl boundary.

### CODE REVIEW

**Comment by rychallener** [comment]
I tested this with uniform atmospheric files and equilibrium files, both given and created. All appear to be working as intended.

**Comment by pcubillos** [comment]
Good, if the tests worked, then go ahead with the merge, but remember to rebase first (there are a couple of commits between the code you grabbed and the most current master).

**Comment by rychallener** [comment]
I'm a little unfamiliar with rebasing, but I did:

git rebase origin/master

and was told that everything is up to date. Should be good to merge then, right? Also github says that there are no conflicts between this branch and the master branch.

**Comment by pcubillos** [comment]
There is a script in here:
https://github.com/exosports/transit/wiki/Transit-Git-Wiki

**Comment by rychallener** [comment]
Ah excellent. Done.

**Pull request merged**
